name: Compile GDE GoZen
on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '0 4 1 * *' # At 04:00 on the 1st of every month
      timezone: Asia/Tokyo
        
env:
  GODOT_VERSION: ${{ vars.GODOT_VERSION }}
 
run-name: Compile GDE

jobs:
  build-gde:
    name: ${{ matrix.platform }} GDE (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.platform == 'windows' && 'msys2 {0}' || 'bash' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-22.04
            target: template_debug
            scons_flags: platform=linux arch=x86_64
          - platform: linux
            os: ubuntu-22.04
            target: template_release
            scons_flags: platform=linux arch=x86_64
          - platform: windows
            os: windows-latest
            target: template_debug
            scons_flags: platform=windows arch=x86_64 use_static_cpp=yes use_mingw=yes
          - platform: windows
            os: windows-latest
            target: template_release
            scons_flags: platform=windows arch=x86_64 use_static_cpp=yes use_mingw=yes
    steps:
      - name: Checkout submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Setting up environment.
      - name: Setup Linux dependencies
        if: matrix.platform == 'linux'
        uses: ./.github/actions/setup-linux-deps

      - name: Setup Windows dependencies
        if: matrix.platform == 'windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-scons mingw-w64-ucrt-x86_64-python make

      # Fetch FFmpeg.
      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg
        with:
          os: ${{ matrix.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # Compile.
      - name: Compile GDE
        working-directory: ./core
        run: scons -j$(nproc) target=${{ matrix.target }} ${{ matrix.scons_flags }}
        
      # Upload
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}_gde_${{ matrix.target }}_x86_64
          path: bin/${{ matrix.platform }}_x86_64
          retention-days: 90
